### ISSUE TITLE
using launch template is failing

### ISSUE THREAD

**Issue by pete911** [pete911/eks-cluster#2]
when using launch template I get the following error:
```
Error: error waiting for EKS Node Group (main:default) creation: NodeCreationFailure: Instances failed to join the kubernetes cluster. Resource IDs: [i-0b4...]
```
Try creating eks launch template manually to see which part is failing

following configuration is failing
```
resource "aws_eks_node_group" "this" {
  ...
    launch_template {
    id      = aws_launch_template.cluster[each.key].id
    version = aws_launch_template.cluster[each.key].default_version
  }
  ...
}
# https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html
resource "aws_launch_template" "cluster" {
  for_each = var.node_groups

  name                   = each.key
  instance_type          = each.value.instance_type
  vpc_security_group_ids = [aws_eks_cluster.this.vpc_config[0].cluster_security_group_id]
  image_id               = data.aws_ami.eks_node.image_id

  block_device_mappings {
    device_name = "/dev/sda1"

    ebs {
      volume_size = 20
    }
  }

  tags = {
    "eks:cluster-name"   = var.cluster_name
    "eks:nodegroup-name" = each.key
  }

  tag_specifications {
    resource_type = "instance"

    tags = {
      Name                 = format("%s-%s", local.name, each.key)
      type                 = local.type_tag
      "eks:cluster-name"   = var.cluster_name
      "eks:nodegroup-name" = each.key
    }
  }
}
```

**Comment by pete911** [comment]
https://wangpp.medium.com/terraform-eks-nodegroups-with-custom-launch-templates-5b6a199947f
this explains why there are multiple launch templates ....

**Comment by yakhyadabo** [comment]
Hi @pete911 , 
I'm facing similar issue, when creating eks cluster with the launch_template. 
`Error: error waiting for EKS Node Group (main:default) creation: NodeCreationFailure: Instances failed to join the kubernetes cluster. 
`

May I know how did you fix it ?

**Comment by pete911** [comment]
Hi @yakhyadabo, this has been fixed when I closed this issue. Do you get the error when you run this project? Did you change any of the settings?

**Comment by yakhyadabo** [comment]
I'm not using this project. I have my own Terraform code base where I'm using launch template. 
I wanted to know if there's any config I miss when using launch_template.

**Comment by pete911** [comment]
ok, it is hard to say, if you are not using this project (maybe clone it and diff against yours) I think in my case (it was long time ago) I was missing user data - https://github.com/pete911/eks-cluster/blob/master/tf/modules/eks/templates/user_data.tpl

**Comment by MeNsaaH** [comment]
@yakhyadabo, I bumped into this issue recently. What fixed it for me was adding the `image_id` to the launch template.

```hcl
# Recommended AMI for the cluster version
data "aws_ssm_parameter" "eks_ami_release_version" {
  name = "/aws/service/eks/optimized-ami/${aws_eks_cluster.this.version}/amazon-linux-2/recommended/image_id"
}

resource "aws_launch_template" "eks_general" {
  name          = "eks-utility-worker-node"
  description   = "Launch template for utility node instance cluster"
  ebs_optimized = true
  image_id      = nonsensitive(data.aws_ssm_parameter.eks_ami_release_version.value)  ## this was missing initially
  user_data     = data.cloudinit_config.eks_general_new.rendered
  key_name      = data.aws_key_pair.this.key_name

  block_device_mappings {
    device_name = "/dev/xvda"

    ebs {
      volume_size           = 50
      volume_type           = "gp2"
      encrypted             = true
      delete_on_termination = true
    }
  }

  tag_specifications {
    resource_type = "instance"

    tags = {
      Name = "eks-worker-node"
    }
  }
}

```

I don't know what changed, but I was able to apply this without the specifying the AMI on cluster version v1.23, but it seems with v1.24, you need to specify the image_id when you use launch_templates.

**Comment by yakhyadabo** [comment]
Hi @MeNsaaH

I fixed the issue by tagging the resources properly. 

**subnets :** 


```
  tags = {
    "kubernetes.io/cluster/${var.cluster_name}" = "shared"
    "kubernetes.io/role/internal-elb" = 1
  }
```

**launch_template :** 

```
  tag_specifications {
    resource_type = "instance"
    tags = {
      "kubernetes.io/cluster/${var.cluster_name}" = "owned"
    }
  }
```
