### ISSUE TITLE
how to pass my public and private cidr block rage

### ISSUE THREAD

**Issue by reddy2018** [pete911/eks-cluster#7]
can you please let me know who to pass my values of 

if i want to pass new cidr block for this?
vpc cidr
public subnet cidr
private subnet cidr rages

also,apply (replace <your-IP>) terraform apply -var='public_access_cidrs=["<your-IP>/32"]'

your ip means, my local system ip(here only i am accesing my eks cluster
)

**Comment by pete911** [comment]
Hi @reddy2018, there's a variable `vpc_address` - https://github.com/pete911/eks-cluster/blob/master/tf/variables.tf#L43 which you can set. This will change the default vpc cidr block. Private and public subnets are calculated dynamically (as mentioned in the readme) here - https://github.com/pete911/eks-cluster/blob/master/tf/modules/vpc/main.tf#L5

If you need this to be manual, feel free to fork the repo and update it according to your needs. Or let me know what exactly you want to achieve and I can have a look if I can make it configurable.

**Comment by reddy2018** [comment]
@pete911 Thank you so much for the quick response.

i am trying to reuse this vpc and eks module for both public and private connections.
meaning that, if one of my client wants to deploy his worker nodes in private subnets and other one wants to deploy public subnets. in that scenario, with out much change in the module section, we can directly pass those changed in the main.tf file.
https://github.com/pete911/eks-cluster/blob/master/tf/main.tf

**Comment by pete911** [comment]
Hi, sorry for late reply, I had a look and I feel that it will be "cleaner" if you just fork the project and modify the subnets. I don't want to add too many options, because I want to keep it easier to use. Also I feel like pods should run in the private subnet by default.
