### ISSUE TITLE
Error: error creating EKS Node Group (ops-monitoring-lab-cluster:ops-monitoring-lab): InvalidRequestException: You are not authorized to launch instances with this launch template. Encoded authorization failure message: 

### ISSUE THREAD

**Issue by reddy2018** [pete911/eks-cluster#8]
Error: error creating EKS Node Group (ops-monitoring-lab-cluster:ops-monitoring-lab): InvalidRequestException: You are not authorized to launch instances with this launch template. Encoded authorization failure message: 0oIhNE5ADnJfdkNem1tZDPyGzhVLXTAiCvkJtKSmdq7oQRVqfIq8wBf019yIG2DXlIuMeFJPzhhKJHioayGCZzmAeGSXKJWrcqHdkeB7cWqXtcsXBX0gNeJS303nHaUyEikTZrBh7pnQ2wRoQ5Fl3P6-Uk_cclIWAvefYXdH53RLgPtr-J3WRf0He6dajz5mx314RKJaTHvi02EpdCKGAbzkY-5ahLWluaRvA65HL1vhVPJTo450esSC5j4eV0DOHbDLdXREA6HmVS2M7bzbyCKrQrGkCwHjC8EqDCFQZA5Dr7a56hv7GJB7kolooWiaPHHkXBNTSqk0f5_jXx0tU8CL_9zY7JGgSY0hckUvJ7YYGqdp2raPSZkvJOPLO5vWDTHPwTwsuOrUhe-hlrzJ5grGIDXDG8-Hv0Jkgb0tDjK30JRis-7AmoKk275JtfSRksJH02P6mnASDakbKnF2O3oWmzEi3rFfCqkhA2Dok5oXiE-Ot1zvTLPatVf7mekAosk4EXc-2PMSV8_bZMG0adHArGy6z6O5fMF56x3X7CkZLfPlK0TYL1E8RY6hFnwmRRFOMRdR1o1-jGoZBI2TxQOuR0ie5NLpf5x2BnIVfGUrYZuAfFcU_WqHiJ3XeqCfFY_mU4Pjl3-e_AfycxjTKUgtfjO_hDq5ugYlvH-j5iyD1JnmYJEe34HMnbBft5nWHWwtNUG1rI4WQZ-rm7wASn4OHoukLgSLcurJ9cTcgJnAlxk5K_V4EzRM7oAcwp77_Ny7_paNyxTsILjHpRzYBdE5G5t1CFp8AeodPvuqs3zy1ZwUncUHHSppRmkiiePIoAqu94avlYBcbn9woGZQgOLAU7c_OytNHDMXM5yfvGOzA-gpuWnZjg
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "5336b8a0-2660-4fe4-b030-ae21a661db48"
│   },
│   Message_: "You are not authorized to launch instances with this launch template. Encoded authorization failure message: 0oIhNE5ADnJfdkNem1tZDPyGzhVLXTAiCvkJtKSmdq7oQRVqfIq8wBf019yIG2DXlIuMeFJPzhhKJHioayGCZzmAeGSXKJWrcqHdkeB7cWqXtcsXBX0gNeJS303nHaUyEikTZrBh7pnQ2wRoQ5Fl3P6-Uk_cclIWAvefYXdH53RLgPtr-J3WRf0He6dajz5mx314RKJaTHvi02EpdCKGAbzkY-5ahLWluaRvA65HL1vhVPJTo450esSC5j4eV0DOHbDLdXREA6HmVS2M7bzbyCKrQrGkCwHjC8EqDCFQZA5Dr7a56hv7GJB7kolooWiaPHHkXBNTSqk0f5_jXx0tU8CL_9zY7JGgSY0hckUvJ7YYGqdp2raPSZkvJOPLO5vWDTHPwTwsuOrUhe-hlrzJ5grGIDXDG8-Hv0Jkgb0tDjK30JRis-7AmoKk275JtfSRksJH02P6mnASDakbKnF2O3oWmzEi3rFfCqkhA2Dok5oXiE-Ot1zvTLPatVf7mekAosk4EXc-2PMSV8_bZMG0adHArGy6z6O5fMF56x3X7CkZLfPlK0TYL1E8RY6hFnwmRRFOMRdR1o1-jGoZBI2TxQOuR0ie5NLpf5x2BnIVfGUrYZuAfFcU_WqHiJ3XeqCfFY_mU4Pjl3-e_AfycxjTKUgtfjO_hDq5ugYlvH-j5iyD1JnmYJEe34HMnbBft5nWHWwtNUG1rI4WQZ-rm7wASn4OHoukLgSLcurJ9cTcgJnAlxk5K_V4EzRM7oAcwp77_Ny7_paNyxTsILjHpRzYBdE5G5t1CFp8AeodPvuqs3zy1ZwUncUHHSppRmkiiePIoAqu94avlYBcbn9woGZQgOLAU7c_OytNHDMXM5yfvGOzA-gpuWnZjg"
│ }
│
│   with module.eng_aws_eks.aws_eks_node_group.this["ops-monitoring-lab"],
│   on .terraform\modules\eng_aws_eks\eng_aws_eks\main.tf line 47, in resource "aws_eks_node_group" "this":
│   47: resource "aws_eks_node_group" "this" {
│
╵

**Comment by reddy2018** [comment]
i am getting this error from yesterday onwards. previosly its working fine for me
is there any change in the module or something in the aws side?

**Comment by pete911** [comment]
hard to say, you need to decode the error message - https://docs.aws.amazon.com/cli/latest/reference/sts/decode-authorization-message.html
